pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run
  volumes:
  - name: docker-sock
    emptyDir: {}
'''
        }
    }
    
    stages {
        stage('Build') {
            steps {
                container('docker') {
                    sh 'docker pull ros:humble'
                    // Add your other docker commands here
                }
            }
        }
        
        stage('Test') {
            steps {
                container('docker') {
                    // Your test commands
                    sh 'echo "Running tests"'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Build completed'
            // Remove cleanWs() or install Workspace Cleanup plugin
        }
        failure {
            echo 'Build failed!'
        }
    }
}