pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: docker
    image: docker:dind
    securityContext:
      privileged: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run
  - name: ros
    image: ros:humble
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
  volumes:
  - name: docker-sock
    emptyDir: {}
'''
        }
    }
    
    environment {
        ROS_WS = '/ros_ws'
        PACKAGE_NAME = 'python_example'
        PACKAGE_DIR = 'python-example'
    }
    
    stages {
        stage('Setup') {
            steps {
                container('ros') {
                    sh '''
                        apt-get update
                        apt-get install -y python3-pip python3-build python3-venv
                        pip3 install uv
                        mkdir -p ${ROS_WS}/src
                        cp -r pkgs/${PACKAGE_DIR} ${ROS_WS}/src/
                    '''
                }
            }
        }
        
        stage('Install Dependencies') {
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}
                        . /opt/ros/humble/setup.sh
                        rosdep update
                        rosdep install --from-paths src --ignore-src -r -y
                    '''
                }
            }
        }
        
        stage('Build with Colcon') {
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}
                        . /opt/ros/humble/setup.sh
                        colcon build --packages-select ${PACKAGE_NAME}
                    '''
                }
            }
        }
        
        stage('Test') {
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}
                        . /opt/ros/humble/setup.sh
                        colcon test --packages-select ${PACKAGE_NAME}
                        colcon test-result --verbose
                    '''
                }
            }
        }
        
        stage('Build Python Wheel') {
            when {
                tag pattern: "v\\d+\\.\\d+\\.\\d+", comparator: "REGEXP"
            }
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}/src/${PACKAGE_DIR}
                        python3 -m build
                        mkdir -p ${WORKSPACE}/artifacts
                        cp dist/*.whl ${WORKSPACE}/artifacts/
                        cp dist/*.tar.gz ${WORKSPACE}/artifacts/ || true
                    '''
                }
            }
        }
        
        stage('Build with uv') {
            when {
                tag pattern: "v\\d+\\.\\d+\\.\\d+", comparator: "REGEXP"
            }
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}/src/${PACKAGE_DIR}
                        uv venv
                        . .venv/bin/activate
                        uv pip install build
                        python3 -m build
                    '''
                }
            }
        }
        
        stage('Create Tarball') {
            when {
                tag pattern: "v\\d+\\.\\d+\\.\\d+", comparator: "REGEXP"
            }
            steps {
                container('ros') {
                    sh '''
                        cd ${ROS_WS}
                        mkdir -p ${WORKSPACE}/artifacts
                        tar czf ${WORKSPACE}/artifacts/${PACKAGE_NAME}-${TAG_NAME}.tar.gz install/${PACKAGE_NAME}/
                    '''
                }
            }
        }
        
        stage('Archive Artifacts') {
            when {
                tag pattern: "v\\d+\\.\\d+\\.\\d+", comparator: "REGEXP"
            }
            steps {
                container('ros') {
                    archiveArtifacts artifacts: 'artifacts/*', fingerprint: true
                }
            }
        }
        
        stage('Publish Release') {
            when {
                tag pattern: "v\\d+\\.\\d+\\.\\d+", comparator: "REGEXP"
            }
            steps {
                container('ros') {
                    script {
                        def version = env.TAG_NAME.replace('v', '')
                        echo "Publishing release ${version}"
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed'
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}